In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# GRB2 SH3

In [29]:
binding_data = pd.read_csv('GRB2-SH3_bind_all_mutants.csv', index_col=0)
binding_data = binding_data[['aa_seq', 'fitness']]
binding_data = binding_data.rename(columns = {'fitness' : 'activity'})

# Filtering out the sequence that appears many times (WT sequence maybe?)
# binding_data = binding_data[binding_data['aa_seq']  != 'TYVQALFDFDPQEDGELGFRRGDFIHVMDNSDPNWWKGACHGQTGMFPRNYVTPVN*']
binding_data = pd.DataFrame(binding_data.groupby('aa_seq')['activity'].mean()).reset_index()
binding_data

/var/folders/34/1pw3__x51kdfyh3vk72f5vc80000gn/T/ipykernel_7079/1555588476.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  binding_data = pd.read_csv('GRB2-SH3_bind_all_mutants.csv', index_col=0)

                                                  aa_seq  activity
0      *YVQALFDFDPQEDGELGFRRGDFIHVMDNSDPNWWKGACHGQTGM... -0.168129
1      *YVQALFDFDPQEDGELGFRRGDFIHVMDNSDPNWWKGACHGQTGM... -0.219692
2      *YVQALFDFDPQEDGELGFRRGDFIHVMDNSDPNWWKGAYHGQTGM...  0.039077
3      *YVQALFDFDPQEDGELGFRRGDFIHVMDNTDPNWWKGACHGQTGM... -0.145315
4      A*VQALFDFDPQEDGELGFRRGDFIHVMDNSDPNWWKGACHGQTGM... -0.569790
...                                                  ...       ...
38259  VYVQALFDFDPQEDRELGFRRGDFIHVMDNSDPNWWKGACHGQTGM... -0.104941
38260  VYVQALFDFDPREDGELGFRRGDFIHVMDNSDPNWWKGACHGQTGM... -0.100175
38261  VYVQALFDFNPQEDGELGFRRGDFIHVMDNSDPNWWKGACHGQTGM... -0.154208
38262  VYVQALFDFYPQEDGELGFRRGDFIHVMDNSDPNWWKGACHGQTGM... -0.159455
38263  VYVQALIDFDPQEDGELGFRRGDFIHVMDNSDPNWWKGACHGQTGM... -0.347853

[38264 rows x 2 columns]

In [31]:
abund_data = pd.read_csv('GRB2-SH3_abund_all_mutants.csv', index_col=0)
abund_data = abund_data[['aa_seq', 'fitness']]
abund_data = abund_data.rename(columns = {'fitness' : 'abundance'})

# Filtering out the sequence that appears many times (WT maybe?)
# abund_data = abund_data[abund_data['aa_seq'] != 'TYVQALFDFDPQEDGELGFRRGDFIHVMDNSDPNWWKGACHGQTGMFPRNYVTPVN*']
abund_data = pd.DataFrame(abund_data.groupby('aa_seq')['abundance'].mean()).reset_index()
abund_data

/var/folders/34/1pw3__x51kdfyh3vk72f5vc80000gn/T/ipykernel_7079/2619215822.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  abund_data = pd.read_csv('GRB2-SH3_abund_all_mutants.csv', index_col=0)

                                                  aa_seq  abundance
0      *YVQALFDADPQEDGELGFRRGDFIHVMDNSDPNWWKGACHGQTGM...  -0.775857
1      *YVQALFDFDLQEDGELGFRRGDFIHVMDNSDPNWWKGACHGQTGM...  -0.794252
2      *YVQALFDFDPGEDGELGFRRGDFIHVMDNSDPNWWKGACHGQTGM...  -0.848891
3      *YVQALFDFDPQEDGALGFRRGDFIHVMDNSDPNWWKGACHGQTGM...  -0.834825
4      *YVQALFDFDPQEDGDLGFRRGDFIHVMDNSDPNWWKGACHGQTGM...  -0.724493
...                                                  ...        ...
69567  YYVQALFDFDPQEDSELGFRRGDFIHVMDNSDPNWWKGACHGQTGM...  -0.542374
69568  YYVQALFDFLPQEDGELGFRRGDFIHVMDNSDPNWWKGACHGQTGM...  -0.183580
69569  YYVQALGDFDPQEDGELGFRRGDFIHVMDNSDPNWWKGACHGQTGM...  -0.633779
69570  YYVQALSDFDPQEDGELGFRRGDFIHVMDNSDPNWWKGACHGQTGM...  -0.119456
69571  YYVQGLFDFDPQEDGELGFRRGDFIHVMDNSDPNWWKGACHGQTGM...  -0.929401

[69572 rows x 2 columns]

In [16]:
len(set(binding_data['aa_seq'].str.removesuffix('*')).difference(set(abund_data['aa_seq'].str.removesuffix('*'))))

32548

In [35]:
merged_data = abund_data.merge(binding_data, on='aa_seq', how='inner')
merged_data['aa_seq'] = merged_data['aa_seq'].str.removesuffix('*')
merged_data = merged_data[['*' not in seq for seq in merged_data['aa_seq']]]
merged_data

                                                 aa_seq  abundance  activity
1     AYVQALFDFDPQEDGELGFRREDFIHVMDNSDPNWWKGACHGQTGM...  -1.200943 -0.325963
2     AYVQALFDFDPQEDGELGFRRGDFIHVMDNSDPNWWKGACHGQIGM...  -0.187139  0.025369
3     AYVQALFDFDPQEDGELGFRRGDFIHVMDNSDPNWWKGACHGQPGM...  -0.813554 -0.494543
4     AYVQALFDFDPQEDGELGFRRGDFIHVMDNSDPNWWKGACHGQTGM...   0.012583 -0.013506
5     AYVQALFDFDPQEDGELGFRRGDFIHVMDNSDPNWWKGACHGQTGM...  -1.046748 -0.614065
...                                                 ...        ...       ...
5711  VYVQALFDFDPQEDGELGFRRGDFIHVMDNSDPNWWKGACHGQTGM...   0.092177 -0.159455
5712  VYVQALFDFDPQEDGELGFRRGDFIHVMDNSDPNWWKGACHGQTGM...  -0.002836 -0.002641
5713  VYVQALFDFDPQEDGELGFRRGDFIHVMDNSDPNWWKGACHGQTGM...  -0.176436 -0.360087
5714  VYVQALFDFDPQEDGELGFRRGDFIHVMDNSDPNWWKGARHGQTGM...  -0.428004  0.084543
5715  VYVQALFDFDPQEDGELGFRRGDFIHVTDNSDPNWWKGACHGQTGM...  -0.059894 -0.159455

[5334 rows x 3 columns]

In [36]:
merged_data.to_csv("GRB2_SH3_wrangled.csv")

# PSD95-PDZ3

In [43]:
binding_data = pd.read_csv('PSD95-PDZ3_bind_all_mutants.csv', index_col=0)
binding_data = binding_data[['aa_seq', 'fitness']]
binding_data = binding_data.rename(columns = {'fitness' : 'activity'})

# Filtering out the sequence that appears many times (WT sequence maybe?)
# binding_data = binding_data[binding_data['aa_seq']  != 'TYVQALFDFDPQEDGELGFRRGDFIHVMDNSDPNWWKGACHGQTGMFPRNYVTPVN*']
print(binding_data['aa_seq'].value_counts())
binding_data = pd.DataFrame(binding_data.groupby('aa_seq')['activity'].mean()).reset_index()
binding_data

aa_seq
PRRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPADLSGELRKGDQILSVNGVDLRNASHEQAAIALKNAGQTVTIIAQYKP*    69
KRRIVIHRGITGLGFNIVGGEDGEGIFISFILAGGPADLSGELRKGDQILSVNGVDLRNASHEQAAIALKNAGQTVTIIAQYKP*     1
PRRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPADLAGELRKGDQILSVLGVDLRNASHEQAAIALKNAGQTVTIIAQYKP*     1
PRRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPADLAGELRKGDQILSVNGCDLRNASHEQAAIALKNAGQTVTIIAQYKP*     1
PRRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPADLAGELRKGDQILSVNGLDLRNASHEQAAIALKNAGQTVTIIAQYKP*     1
                                                                                         ..
PRRIVIHRGSTGRGFNIVGGEDGEGIFISFILAGGPADLSGELRKGDQILSVNGVDLYNASHEQAAIALKNAGQTVTIIAQYKP*     1
PRRIVIHRGSTGRGFNIVGGEDGEGIFISFILAGGPADLSGELRKGDQILSVNGVDL*NASHEQAAIALKNAGQTVTIIAQYKP*     1
PRRIVIHRGSTGRGFNIVGGEDGEGIFISFILAGGPADLSGELRKGDQILSVNGVDLVNASHEQAAIALKNAGQTVTIIAQYKP*     1
PRRIVIHRGSTGRGFNIVGGEDGEGIFISFILAGGPADLSGELRKGDQILSVNGVDLGNASHEQAAIALKNAGQTVTIIAQYKP*     1
FRRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPADLAGELRKGDQILSVNGVDLRNASHEQAAIALKNAGQTVTIIAQYKP*     1
Name: count, Length: 8540, dtype: int64

                                                 aa_seq  activity
0     *RRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPADLAGELRKG... -0.928196
1     *RRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPADLSGELRKG... -1.131819
2     *RRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPADLSGELRKG... -0.757440
3     ARRIVIHRGITGLGFNIVGGEDGEGIFISFILAGGPADLSGELRKG... -0.142638
4     ARRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPADLAGELRKG... -0.238705
...                                                 ...       ...
8535  WRRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPADLSGELRKG... -1.128276
8536  WRRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPADLSGELRKG... -0.288732
8537  WRRIVIHRGSTGLVFNIVGGEDGEGIFISFILAGGPADLSGELRKG... -0.656023
8538  YRRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPADLAGELRKG... -0.421161
8539  YRRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPADLSGELRKG... -0.147614

[8540 rows x 2 columns]

In [40]:
abund_data = pd.read_csv('PSD95-PDZ3_abundance_all_mutants.csv', index_col=0)
abund_data = abund_data[['aa_seq', 'fitness']]
abund_data = abund_data.rename(columns = {'fitness' : 'abundance'})

# Filtering out the sequence that appears many times (WT maybe?)
# abund_data = abund_data[abund_data['aa_seq'] != 'TYVQALFDFDPQEDGELGFRRGDFIHVMDNSDPNWWKGACHGQTGMFPRNYVTPVN*']
abund_data = pd.DataFrame(abund_data.groupby('aa_seq')['abundance'].mean()).reset_index()
abund_data

                                                 aa_seq  abundance
0     *RRIVIHRGITGLGFNIVGGEDGEGIFISFILAGGPADLSGELRKG...  -0.645964
1     *RRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPADLSGELRKG...  -0.557401
2     ARRIRIHRGSTGLGFNIVGGEDGEGIFISFILAGGPADLSGELRKG...  -0.084780
3     ARRIVIHRGITGLGFNIVGGEDGEGIFISFILAGGPADLSGELRKG...  -0.039601
4     ARRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPADLAGELRKG...   0.011315
...                                                 ...        ...
7203  WRRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPADLSGELRKG...  -0.046368
7204  WRRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPADLSGELRKG...  -0.765344
7205  WRRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPADLSGELRKG...  -0.080317
7206  YRRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPADLSGELRKG...  -0.113222
7207  YRRIVIHRGSTGLVFNIVGGEDGEGIFISFILAGGPADLSGELRKG...  -0.932206

[7208 rows x 2 columns]

In [39]:
merged_data = abund_data.merge(binding_data, on='aa_seq', how='inner')
merged_data['aa_seq'] = merged_data['aa_seq'].str.removesuffix('*')
merged_data = merged_data[['*' not in seq for seq in merged_data['aa_seq']]]
merged_data

                                                 aa_seq  abundance  activity
1     ARRIVIHRGITGLGFNIVGGEDGEGIFISFILAGGPADLSGELRKG...  -0.039601 -0.142638
2     ARRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPADLAGELRKG...   0.011315 -0.238705
3     ARRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPADLSGELRKG...   0.135278 -0.023782
4     ARRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPADLSGELRKG...  -1.239825 -1.030962
5     ARRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPADLSGELRKG...   0.066805 -0.125567
...                                                 ...        ...       ...
5660  WRRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPADLAGELRKG...  -0.053280 -0.341028
5661  WRRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPADLSGELRKG...  -0.046368 -0.226553
5662  WRRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPADLSGELRKG...  -0.765344 -1.128276
5663  WRRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPADLSGELRKG...  -0.080317 -0.288732
5664  YRRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPADLSGELRKG...  -0.113222 -0.147614

[5528 rows x 3 columns]

In [42]:
merged_data.to_csv("PSD95_PDZ3_wrangled.csv")